config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root "welcome#index"
  require 'sidekiq/web'
  require 'sidetiq/web'

  mount Sidekiq::Web, at: '/sidekiq'
  # mount Sidetiq::Web, at: '/sidetiq'

  resources :products do
    member do
      post :add_to_cart
    end
    collection do
      get :search
    end
  end

  namespace :admin do
    resources :products
    resources :categories
    resources :orders do
      member do
        post :cancel
        post :ship
        post :shipped
        post :return
      end
    end
  end

  resources :carts do
    collection do
      delete :clean
      post :checkout
    end
  end

  namespace :account do
    resources :orders
  end

  resources :cart_items

  resources :orders do
    member do
      post :pay_with_wechat
      post :pay_with_alipay
      post :apply_to_cancel
    end
  end

  namespace :api, :defaults => { :format => :json } do
    namespace :v1 do
      resources :products do
        collection do
          get :search
        end
      end
      resources :categories
      resources :photos
    end
  end
end

app/models/order.rb
class Order < ApplicationRecord
  belongs_to :user
  has_many :product_lists

  before_create :generate_token

  include AASM

  aasm do
    state :order_placed, :initial => true
    state :paid
    state :shipping
    state :shipped
    state :good_returned
    state :order_canceled

    event :make_payment, :after_commit => :pay! do
      transitions :from => :order_placed, :to => :paid
    end

    event :ship do
      transitions :from => :paid, :to => :shipping
    end

    event :deliver do
      transitions :from => :shipping, :to => :shipped
    end

    event :return_good do
      transitions :from => :shipped, :to => :good_returned
    end

    event :cancel_order do
      transitions :from => [:order_placed, :paid], :to => :order_canceled
    end
  end

  def generate_token
    self.token = SecureRandom.uuid
  end

  def set_payment_with!(method)
    self.update_columns(payment_method: method)
  end

  def pay!
    self.update_columns(is_paid: true)
  end
end

app/controllers/account/orders_controller.rb
class Account::OrdersController < ApplicationController
  def index
    @orders = current_user.orders.order("id DESC")
  end
end

app/controllers/admin/orders_controller.rb
class Admin::OrdersController < ApplicationController
  before_action :authenticate_user!
  before_action :admin_required
  layout "admin"

  def index
    @orders = Order.includes(:user).all.order("id DESC")
  end

  def show
    @order = Order.find(params[:id])
    @product_lists = @order.product_lists
  end

  def ship
    @order = Order.find(params[:id])
    @order.ship!
    OrderMailer.notify_ship(@order).deliver!
    redirect_to :back
  end

  def shipped
    @order = Order.find(params[:id])
    @order.deliver!
    redirect_to :back
  end

  def cancel
    @order = Order.find(params[:id])
    @order.cancel_order!
    OrderMailer.notify_cancel(@order).deliver!
    redirect_to :back
  end

  def return
    @order = Order.find(params[:id])
    @order.return_good!
    redirect_to :back
  end
end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController

  def show
    @order = Order.find_by_token(params[:id])
    @product_lists = @order.product_lists
  end

  def create
    @order = Order.new(order_params)
    @order.user = current_user
    @order.total = current_cart.total_price
    if @order.save
      current_cart.cart_items.each do |cart_item|
        product_list = ProductList.new
        product_list.order = @order
        product_list.product_name = cart_item.product.title
        product_list.product_price = cart_item.product.price
        product_list.quantity = cart_item.quantity
        product_list.save
      end
      current_cart.clean!
      OrderMailer.notify_order_placed(@order).deliver!
      redirect_to order_path(@order.token)
    else
      render "carts/checkout"
    end
  end

  def pay_with_wechat
    @order = Order.find_by_token(params[:id])
    @order.set_payment_with!("wechat")
    @order.make_payment!
    redirect_to :back
    flash[:notice] = "微信支付成功"
  end

  def pay_with_alipay
    @order = Order.find_by_token(params[:id])
    @order.set_payment_with!("alipay")
    @order.make_payment!
    redirect_to :back
    flash[:notice] = "支付宝支付成功"
  end

  def apply_to_cancel
    @order = Order.find_by_token(params[:id])
    OrderMailer.apply_cancel(@order).deliver!
    flash[:notice] = "已提交申请"
    redirect_to :back
  end

  private

  def order_params
    params.require(:order).permit(:billing_name, :billing_address, :shipping_name, :shipping_address, :total)
  end
end

app/helpers/account/orders_helper.rb
module Account::OrdersHelper
end

app/helpers/admin/orders_helper.rb
module Admin::OrdersHelper
end

app/helpers/orders_helper.rb
module OrdersHelper
  def render_order_paid_state(order)
    if order.is_paid?
      "已付款"
    else
      "未付款"
    end
  end
end

app/views/admin/orders/_state_option.html.erb
<div style="padding:10px; float:right;">

  <% case order.aasm_state %>
  <% when "order_placed" %>
    <%= link_to("取消订单",
                cancel_admin_order_path(order),
                class: "btn btn-default btn-sm", method: :post) %>

  <% when "paid" %>
    <%= link_to("取消订单",
                cancel_admin_order_path(order),
                class: "btn btn-default btn-sm", method: :post) %>
    <%= link_to("出货",
                ship_admin_order_path(order),
                class: "btn btn-default btn-sm", method: :post) %>

  <% when "shipping" %>
    <%= link_to("设为已出货",
                shipped_admin_order_path(order),
                class: "btn btn-default btn-sm", method: :post) %>

  <% when "shipped" %>
    <%= link_to("退货",
                return_admin_order_path(order),
                class: "btn btn-default btn-sm", method: :post) %>

  <% when "order_cancelled" %>
    <span class="label label-default">订单已取消</span>

  <% when "good_returned" %>
    <span class="label label-default">已退货</span>

  <% end %>

</div>

app/views/admin/orders/index.html.erb
<h2>我的订单</h2>

<table class="table table-bordered">
  <thead>
    <tr>
      <th>订单编号</th>
      <th>创建时间</th>
      <th>订购人</th>
      <th>订单状态</th>
    </tr>
  </thead>
  <tbody>
    <% @orders.each do |order| %>
      <tr>
        <td><%= link_to(order.id, admin_order_path(order)) %></td>
        <td><%= order.created_at %></td>
        <td><%= order.user.email %></td>
        <td><%= order.aasm_state %></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/admin/orders/show.html.erb
<h2>商品信息(<%= render_order_paid_state(@order) %>)</h2>
<%= render "admin/orders/state_option", order: @order %>

<table class="table table-bordered">
  <thead>
    <tr>
      <th>商品信息</th>
      <th>单价</th>
      <th>数量</th>
    </tr>
  </thead>
  <tbody>
    <% @product_lists.each do |product_list| %>
      <tr>
        <td><%= product_list.product_name %></td>
        <td><%= product_list.product_price %></td>
        <td><%= product_list.quantity %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<div class="clearfix">
  <h2 class="pull-right">
    合计 <%= @order.total %> 元
  </h2>
</div>

<h2>订单信息</h2>
<div class="panel panel-default">
  <div class="panel-heading">订购人</div>
  <div class="panel-body">
    <%= @order.billing_name %> - <%= @order.billing_address %>
  </div>
</div>
<div class="panel panel-default">
  <div class="panel-heading">收件人</div>
  <div class="panel-body">
    <%= @order.shipping_name %> - <%= @order.shipping_address %>
  </div>
</div>

<% if !@order.is_paid? %>
  <%= link_to("微信付款", pay_with_wechat_order_path, method: :post, class:"btn btn-info btn-lg pull-right") %>
  <%= link_to("支付宝付款", pay_with_alipay_order_path, method: :post, class:"btn btn-info btn-lg pull-right") %>
<% else %>
  <h3>此订单已付款</h3>
<% end %>