config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root "welcome#index"
  require 'sidekiq/web'
  require 'sidetiq/web'

  mount Sidekiq::Web, at: '/sidekiq'
  # mount Sidetiq::Web, at: '/sidetiq'

  resources :products do
    member do
      post :add_to_cart
    end
    collection do
      get :search
    end
  end

  namespace :admin do
    resources :products
    resources :categories
    resources :orders do
      member do
        post :cancel
        post :ship
        post :shipped
        post :return
      end
    end
  end

  resources :carts do
    collection do
      delete :clean
      post :checkout
    end
  end

  namespace :account do
    resources :orders
  end

  resources :cart_items

  resources :orders do
    member do
      post :pay_with_wechat
      post :pay_with_alipay
      post :apply_to_cancel
    end
  end

  namespace :api, :defaults => { :format => :json } do
    namespace :v1 do
      resources :products do
        collection do
          get :search
        end
      end
      resources :categories
      resources :photos
    end
  end
end

app/models/category.rb
class Category < ApplicationRecord
  has_many :category_prodcut_relationships
  has_many :products, :through => :category_prodcut_relationships
  mount_uploader :category_image, WxIntroUploader
end

app/controllers/admin/categories_controller.rb
class Admin::CategoriesController < ApplicationController
  before_action :authenticate_user!
  before_action :admin_required
  layout "admin"

  def index
    @categories = Category.includes(:products).all
  end

  def new
    @category = Category.new
  end

  def show
    @category = Category.find(params[:id])
    @products = @category.products
  end

  def create
    @category = Category.new(category_params)
    if @category.save
      redirect_to admin_categories_path
    else
      render :new
    end
  end

  def edit
    @category = Category.find(params[:id])
  end

  def update
    @category = Category.find(params[:id])
    if @category.update(category_params)
      redirect_to admin_categories_path
    else
      render :edit
    end
  end

  def destroy
    @category = Category.find(params[:id])
    @category.destroy
    redirect_to admin_categories_path
  end

  private

  def category_params
    params.require(:category).permit(:name, :category_image, :category_title, :product_ids => [])
  end
end

app/controllers/api/v1/categories_controller.rb
class Api::V1::CategoriesController < ApplicationController
  def index
    @categories = Category.includes(:products).all
  end

  def show
    @category = Category.find(params[:id])
    @products = @category.products
  end
end

app/helpers/admin/categories_helper.rb
module Admin::CategoriesHelper
end

app/helpers/api/v1/categories_helper.rb
module Api::V1::CategoriesHelper
end

app/views/admin/categories/_form.html.erb
<%= f.input :name %>
<%= f.input :category_title %>
<%= f.label :"选择产品" %>
<%= f.select :product_ids, Product.all.map{ |p| [p.title, p.id] }, {}, :multiple => true, :class => "form-control" %>
<%= f.input :category_image%>

app/views/admin/categories/edit.html.erb
<h1>编辑分类</h1>

<%= simple_form_for [:admin, @category] do |f| %>
  <%= render partial:"form", locals:{f: f} %>
  <% if @category.category_image.present? %>
    <%= image_tag(@category.category_image.medium.url, class:"thumbnail") %>
  <% else %>
    <%= image_tag("http://placehold.it/200x100&text=No Pic", class:"thumbnail") %>
  <% end %>
  <div class="form-actions">
    <%= f.submit %>
  </div>
<% end %>


<script>
  $("#category_product_ids").select2( { theme: "bootstrap"} );
</script>

app/views/admin/categories/index.html.erb
<h2> 分类列表 </h2>

<div class="pull-right">
  <%= link_to '新的分类', new_admin_category_path, class: 'btn btn-primary'%>
</div>

<table class="table table-bordered">
  <thead>
    <tr>
      <th>#</th>
      <th>分类名称</th>
      <th>海报</th>
      <th>海报文字</th>
      <th colspan="2">设置</th>
    </tr>
  </thead>
  <tbody>
    <% @categories.each do |category| %>
    <tr>
      <td><%= category.id %></td>
      <td><%= link_to(category.name, admin_category_path(category)) %></td>
      <td>
        <%= link_to admin_category_path(category) do %>
          <% if category.category_image.present? %>
            <%= image_tag(category.category_image.medium.url, class:"thumbnail", style:"width:120px;") %>
          <% else %>
            <%= image_tag("http://placehold.it/200x100&text=No Pic", class:"thumbnail") %>
          <% end %>
        <% end %>
      </td>
      <td><%= category.category_title %></td>
      <td>
        <%= link_to '编辑',edit_admin_category_path(category), class:"btn btn-info btn-xs" %>
        <%= link_to '删除',admin_category_path(category),method: :delete, data: {confirm: '确定删除？'}, class:"btn btn-danger btn-xs"%></td>
    </tr>
    <% end %>
  </tbody>
</table>

app/views/admin/categories/new.html.erb
<h1>新增分类</h1>

<%= simple_form_for [:admin, @category] do |f| %>
  <%= render partial:"form", locals:{f: f} %>
  <div class="form-actions">
    <%= f.submit %>
  </div>
<% end %>


<script>
  $("#category_product_ids").select2( { theme: "bootstrap"} );
</script>

app/views/admin/categories/show.html.erb
<h2><%= @category.name %>的所有商品：</h2>

<% @products.each do |product| %>
  <div class="col-md-3">
    <%= link_to product_path(product) do %>
      <% if product.photos.present? %>
        <%= image_tag(product.photos[0].avatar.thumb.url, class: "thumbnail") %>
      <% else %>
        <%= image_tag("http://placehold.it/200x200&text=No Pic", class:"thumbnail") %>
      <% end %>
    <% end %>
    <%= link_to(product.title, admin_product_path(product)) %>
    ¥ <%= product.price %> 元
  </div>
<% end %>