config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root "welcome#index"
  require 'sidekiq/web'
  require 'sidetiq/web'

  mount Sidekiq::Web, at: '/sidekiq'
  # mount Sidetiq::Web, at: '/sidetiq'

  resources :products do
    member do
      post :add_to_cart
    end
    collection do
      get :search
    end
  end

  namespace :admin do
    resources :products
    resources :categories
    resources :orders do
      member do
        post :cancel
        post :ship
        post :shipped
        post :return
      end
    end
  end

  resources :carts do
    collection do
      delete :clean
      post :checkout
    end
  end

  namespace :account do
    resources :orders
  end

  resources :cart_items

  resources :orders do
    member do
      post :pay_with_wechat
      post :pay_with_alipay
      post :apply_to_cancel
    end
  end

  namespace :api, :defaults => { :format => :json } do
    namespace :v1 do
      resources :products do
        collection do
          get :search
        end
      end
      resources :categories
      resources :photos
    end
  end
end

app/models/product.rb
class Product < ApplicationRecord
  has_many :category_prodcut_relationships
  has_many :categories, :through => :category_prodcut_relationships
  has_many :photos
  accepts_nested_attributes_for :photos
  mount_uploader :detail_image, DetailImgaeUploader

  if Rails.env.production? #远端
    scope :random8, -> { limit(8).order("RAND()") }
  elsif Rails.env.development? #本地
    scope :random8, -> { limit(8).order("RANDOM()") }
  end  
end

app/controllers/admin/products_controller.rb
class Admin::ProductsController < ApplicationController
  before_action :authenticate_user!
  before_action :admin_required
  layout "admin"

  def index
    @products = Product.includes(:categories).all
  end

  def show
    @product = Product.find(params[:id])
  end

  def new
    @product = Product.new
    @photo = @product.photos.build
  end

  def edit
    @product = Product.find(params[:id])
  end

  def create
    @product = Product.new(product_params)
    if @product.save
      if params[:photos] != nil
        params[:photos]['avatar'].each do |a|
          @photo = @product.photos.create(:avatar => a)
        end
      end
      redirect_to admin_products_path
    else
      render :new
    end
  end

  def update
    @product = Product.find(params[:id])
    if params[:photos] != nil
      @product.photos.destroy_all #need to destroy old pics first
      params[:photos]['avatar'].each do |a|
        @picture = @product.photos.create(:avatar => a)
      end
      @product.update(product_params)
      redirect_to admin_products_path
      flash[:notice] = "商品已更新"
    elsif @product.update(product_params)
      redirect_to admin_products_path
      flash[:notice] = "商品已更新"
    else
      render :edit
    end
  end

  def destroy
    @product = Product.find(params[:id])
    @product.destroy
    redirect_to admin_products_path
  end

  private

  def product_params
    params.require(:product).permit(:title, :description, :price, :quantity, :detail_image, :detail, :category_ids => [])
  end

end

app/controllers/api/v1/products_controller.rb
class Api::V1::ProductsController < ApiController
  before_action :validate_search_key, only: [:search]

  def index
    @search = Product.ransack(params[:q])
    @products = @search.result.includes(:categories, :photos)
    if params[:name].present?
      @category = Category.find_by(:name => params[:name])
      if @category.present?
        @products = @category.products
      end
    end
  end

  def show
    @product = Product.find(params[:id])
    @photos = @product.photos.all
    @categories = @product.categories
  end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  before_action :validate_search_key, only: [:search]

  def index
    @search = Product.ransack(params[:q])
    @products = @search.result.includes(:categories, :photos).paginate(:page => params[:page], :per_page => 12 )
    if params[:name].present?
      @category = Category.find_by(:name => params[:name])
      if @category.present?
        @products = @category.products.paginate(:page => params[:page], :per_page => 12 )
      end
    end
    @suggests = Product.random8
  end

  def show
    @product = Product.find(params[:id])
    @photos = @product.photos.all
  end

  def add_to_cart
    @product = Product.find(params[:id])
    if !current_cart.products.include?(@product)
      current_cart.add_product_to_cart(@product)
    end
    flash[:notice] = "已加入购物车"
    redirect_to :back
  end

  def search
    if @query_string.present?
      search_result = Product.ransack(@search_criteria).result(:distinct => true)
      @products = search_result.paginate(:page => params[:page], :per_page => 8 )
    end
  end

  protected

  def validate_search_key
    @query_string = params[:q].gsub(/\\|\'|\/|\?/, "") if params[:q].present?
    @search_criteria = search_criteria(@query_string)
  end

  def search_criteria(query_string)
    { :title_or_description_cont => query_string }
  end
end

app/helpers/admin/products_helper.rb
module Admin::ProductsHelper
end

app/helpers/api/v1/products_helper.rb
module Api::V1::ProductsHelper
end

app/helpers/products_helper.rb
module ProductsHelper
  def render_highlight_content(product,query_string)
    excerpt_cont = excerpt(product.title, query_string, radius: 500)
    highlight(excerpt_cont, query_string)
  end
end

app/views/admin/products/_form.html.erb
<%= f.association :categories, as: :check_boxes %>
<%= f.input :title %>
<%= f.input :description %>
<%= f.input :price %>
<%= f.input :detail_image %>
<%= f.input :quantity %>
<%= f.label :"多图上传" %>
<%= f.file_field :avatar, :multiple => true, name: "photos[avatar][]" %>
<br/>
<%= f.label :"选择分类" %>
<%= f.select :category_ids, Category.all.map{ |c| [c.name, c.id] }, {}, :multiple => true, :class => "form-control" %>
<%= f.input :detail, as: :ckeditor, language:'zh-CN', label:'图文详情' %>

app/views/admin/products/edit.html.erb
<h1>编辑商品</h1>

<div class="col-md-6 col-center">
  <%= simple_form_for [:admin, @product] do |f| %>
    <%= render partial: "form", locals: { :f => f } %>
      <% if @product.photos.present? %>
        <span>目前商品图</span> <br>
        <% @product.photos.each do |p| %>
          <%= image_tag p.avatar.thumb.url %><br>
        <% end %>
      <% else %>
        <%= image_tag("http://placehold.it/200x200&text=No Pic", class:"thumbnail") %>
      <% end %>
    <%= f.submit "保存", data:{disable_with:"正在保存.."}, class:"btn btn-info btn-lg" %>
  <% end %>
</div>


<script>
  $("#product_category_ids").select2( { theme: "bootstrap"} );
</script>

app/views/admin/products/index.html.erb
<%= link_to("新增商品", new_admin_product_path, class:"btn btn-success btn-lg") %>

<table class="table table-bordered">
  <thead>
    <tr>
      <th>商品</th>
      <th>详情</th>
      <th>价格</th>
      <th>库存</th>
      <th>操作</th>
    </tr>
  </thead>
  <tbody>
    <% @products.each do |product| %>
      <tr>
        <td>
          <div class="col-md-6">
            <%= link_to product_path(product) do %>
              <% if product.photos.present? %>
                <%= image_tag(product.photos[0].avatar.thumb.url, class: "thumbnail", style:"width:100px;") %>
              <% else %>
                <%= image_tag("http://placehold.it/200x200&text=No Pic", class:"thumbnail") %>
              <% end %>
            <% end %>
          </div>
          <div class="col-md-6">
            <%= link_to(product.title, admin_product_path(product)) %>
          </div>
        </td>
        <td>
          <%= product.description %>
        </td>
        <td><%= product.price %></td>
        <td><%= product.quantity %></td>
        <td>
          <%= link_to("编辑", edit_admin_product_path(product), class:"btn btn-info btn-xs") %>
          <%= link_to("删除", admin_product_path(product), method: :delete, class:"btn btn-danger btn-xs", data:{confirm:"确认删除？"}) %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/admin/products/new.html.erb
<h1>新增商品</h1>

<div class="col-md-6 col-center">
  <%= simple_form_for [:admin, @product] do |f| %>
    <%= render partial: "form", locals: { :f => f } %>
    <%= f.submit "保存", data:{disable_with:"正在保存.."}, class:"btn btn-info btn-lg" %>
  <% end %>
</div>


<script>
  $("#product_category_ids").select2( { theme: "bootstrap"} );
</script>

app/views/admin/products/show.html.erb
<h2><%= @product.title %></h2>
<h3><%= @product.description %></h3>