config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root "welcome#index"
  require 'sidekiq/web'
  require 'sidetiq/web'

  mount Sidekiq::Web, at: '/sidekiq'
  # mount Sidetiq::Web, at: '/sidetiq'

  resources :products do
    member do
      post :add_to_cart
    end
    collection do
      get :search
    end
  end

  namespace :admin do
    resources :products
    resources :categories
    resources :orders do
      member do
        post :cancel
        post :ship
        post :shipped
        post :return
      end
    end
  end

  resources :carts do
    collection do
      delete :clean
      post :checkout
    end
  end

  namespace :account do
    resources :orders
  end

  resources :cart_items

  resources :orders do
    member do
      post :pay_with_wechat
      post :pay_with_alipay
      post :apply_to_cancel
    end
  end

  namespace :api, :defaults => { :format => :json } do
    namespace :v1 do
      resources :products do
        collection do
          get :search
        end
      end
      resources :categories
      resources :photos
    end
  end
end

app/models/product.rb
class Product < ApplicationRecord
  has_many :category_prodcut_relationships
  has_many :categories, :through => :category_prodcut_relationships
  has_many :photos
  accepts_nested_attributes_for :photos
  mount_uploader :detail_image, DetailImgaeUploader

  if Rails.env.production? #远端
    scope :random8, -> { limit(8).order("RAND()") }
  elsif Rails.env.development? #本地
    scope :random8, -> { limit(8).order("RANDOM()") }
  end  
end

app/controllers/admin/products_controller.rb
class Admin::ProductsController < ApplicationController
  before_action :authenticate_user!
  before_action :admin_required
  layout "admin"

  def index
    @products = Product.includes(:categories).all
  end

  def show
    @product = Product.find(params[:id])
  end

  def new
    @product = Product.new
    @photo = @product.photos.build
  end

  def edit
    @product = Product.find(params[:id])
  end

  def create
    @product = Product.new(product_params)
    if @product.save
      if params[:photos] != nil
        params[:photos]['avatar'].each do |a|
          @photo = @product.photos.create(:avatar => a)
        end
      end
      redirect_to admin_products_path
    else
      render :new
    end
  end

  def update
    @product = Product.find(params[:id])
    if params[:photos] != nil
      @product.photos.destroy_all #need to destroy old pics first
      params[:photos]['avatar'].each do |a|
        @picture = @product.photos.create(:avatar => a)
      end
      @product.update(product_params)
      redirect_to admin_products_path
      flash[:notice] = "商品已更新"
    elsif @product.update(product_params)
      redirect_to admin_products_path
      flash[:notice] = "商品已更新"
    else
      render :edit
    end
  end

  def destroy
    @product = Product.find(params[:id])
    @product.destroy
    redirect_to admin_products_path
  end

  private

  def product_params
    params.require(:product).permit(:title, :description, :price, :quantity, :detail_image, :detail, :category_ids => [])
  end

end

app/controllers/api/v1/products_controller.rb
class Api::V1::ProductsController < ApiController
  before_action :validate_search_key, only: [:search]

  def index
    @search = Product.ransack(params[:q])
    @products = @search.result.includes(:categories, :photos)
    if params[:name].present?
      @category = Category.find_by(:name => params[:name])
      if @category.present?
        @products = @category.products
      end
    end
  end

  def show
    @product = Product.find(params[:id])
    @photos = @product.photos.all
    @categories = @product.categories
  end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  before_action :validate_search_key, only: [:search]

  def index
    @search = Product.ransack(params[:q])
    @products = @search.result.includes(:categories, :photos).paginate(:page => params[:page], :per_page => 12 )
    if params[:name].present?
      @category = Category.find_by(:name => params[:name])
      if @category.present?
        @products = @category.products.paginate(:page => params[:page], :per_page => 12 )
      end
    end
    @suggests = Product.random8
  end

  def show
    @product = Product.find(params[:id])
    @photos = @product.photos.all
  end

  def add_to_cart
    @product = Product.find(params[:id])
    if !current_cart.products.include?(@product)
      current_cart.add_product_to_cart(@product)
    end
    flash[:notice] = "已加入购物车"
    redirect_to :back
  end

  def search
    if @query_string.present?
      search_result = Product.ransack(@search_criteria).result(:distinct => true)
      @products = search_result.paginate(:page => params[:page], :per_page => 8 )
    end
  end

  protected

  def validate_search_key
    @query_string = params[:q].gsub(/\\|\'|\/|\?/, "") if params[:q].present?
    @search_criteria = search_criteria(@query_string)
  end

  def search_criteria(query_string)
    { :title_or_description_cont => query_string }
  end
end

app/helpers/admin/products_helper.rb
module Admin::ProductsHelper
end

app/helpers/api/v1/products_helper.rb
module Api::V1::ProductsHelper
end

app/helpers/products_helper.rb
module ProductsHelper
  def render_highlight_content(product,query_string)
    excerpt_cont = excerpt(product.title, query_string, radius: 500)
    highlight(excerpt_cont, query_string)
  end
end

app/views/products/index.html.erb
<%= form_tag products_path,method: :get do %>
  <%= label_tag :筛选分类 %>
  <%= text_field_tag :name %>
  <%= submit_tag "确定" %>
<% end %>

<div class= "search">
  <%= search_form_for @search do |f| %>
    <%= f.label :ransack搜索商品 %>
    <%= f.search_field :title_or_description_cont %>
    <%= f.submit %>
  <% end %>
</div>
<!-- Split button -->
<div class="btn-group col-md-12" style="margin-bottom:20px;">
  <button type="button" class="btn btn-info">
    所有商品
  </button>
  <button type="button" class="btn btn-info dropdown-toggle" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
    <span class="caret"></span>
    <span class="sr-only">Toggle Dropdown</span>
  </button>
  <ul class="dropdown-menu">
    <li>
      <%= sort_link @search, :quantity, "库存排序" %>
    </li>
    <li>
      <%= sort_link @search, :price, "价格排序" %>
    </li>
    <li>
      <%= sort_link @search, :created_at, "时间顺序" %>
    </li>
  </ul>
</div>

<% @products.each do |product| %>
  <div class="col-md-3">
    <%= link_to product_path(product) do %>
      <% if product.photos.present? %>
        <%= image_tag(product.photos[0].avatar.thumb.url, class: "thumbnail") %>
      <% else %>
        <%= image_tag("http://placehold.it/200x200&text=No Pic", class:"thumbnail") %>
      <% end %>
    <% end %>
    <%= link_to(product.title, admin_product_path(product)) %>
    ¥ <%= product.price %> 元
  </div>
<% end %>

<div class="col-md-12 text-center">
  <%= will_paginate @collection, renderer: BootstrapPagination::Rails %>
</div>


<h2 style="margin-top:700px;" class="text-center">随机推荐8个</h2>
<% @suggests.each do |product| %>
  <div class="col-md-3">
    <%= link_to product_path(product) do %>
      <% if product.photos.present? %>
        <%= image_tag(product.photos[0].avatar.thumb.url, class: "thumbnail") %>
      <% else %>
        <%= image_tag("http://placehold.it/200x200&text=No Pic", class:"thumbnail") %>
      <% end %>
    <% end %>
    <%= link_to(product.title, admin_product_path(product)) %>
    ¥ <%= product.price %> 元
  </div>
<% end %>

app/views/products/search.html.erb
<% if @products.blank? %>
  <h3>没有找到您想要的信息...</h3>
<% else %>
  <h3>找到 <%= @products.count %> 个符合 "<%= @query_string %>" 的商品</h3>
  <% @products.each do |product| %>
    <div class="col-md-3">
      <%= link_to product_path(product) do %>
        <% if product.photos.present? %>
          <%= image_tag(product.photos[0].avatar.thumb.url, class: "thumbnail") %>
        <% else %>
          <%= image_tag("http://placehold.it/200x200&text=No Pic", class:"thumbnail") %>
        <% end %>
      <% end %>
      <% if render_highlight_content(product, @query_string).blank? %>
        <%= link_to(product.title, admin_product_path(product)) %>
      <% else %>
        <%= link_to(render_highlight_content(product, @query_string), admin_product_path(product)) %>
      <% end %>
      ¥ <%= product.price %> 元
    </div>
  <% end %>
  <div class="col-md-12 text-center">
    <%= will_paginate @collection, renderer: BootstrapPagination::Rails %>
  </div>
<% end %>

app/views/products/show.html.erb
<section class="image-box">
  <div class="row">
    <div class="col-md-12">
      <div class="col-md-6">
        <% if @photos.present? %>
          <% @photos.each_with_index do |p, index| %>
            <% if index == 0 %>
              <div class="col-md-12">
                <%= image_tag p.avatar.medium.url %>
              </div>
            <% else %>
              <div class="col-md-3 col-sm-6 col-xs-6">
                <%= image_tag p.avatar.thumb.url %>
              </div>
            <% end %>
          <% end %>
        <% else %>
          <%= image_tag("http://placehold.it/400x400&text=No Pic", class: "thumbnail") %>
        <% end %>
      </div>
      <div class="col-md-6">
        <h1><%= @product.title %></h1>
        <h4 class="ckeditor"><%= simple_format(@product.description) %></h4>
        <h2>¥ <%= @product.price %> 元</h2>
        <% if @product.quantity > 0 %>
          <p>库存 <%= @product.quantity %></p>
        <% else %>
          <p>商品已售罄</p>
        <% end %>
        <%= link_to("加入购物车", add_to_cart_product_path(@product), method: :post, class:"btn btn-danger btn-lg") %>
      </div>
    </div>
  </div>
</section>

<section class="detail-box">
  <div class="row">
    <div class="col-md-12">
      <div class="col-md-9 ckeditor">
        <% if @product.detail.present? %>
          <%= simple_format(@product.detail) %>
        <% else %>
          <%= image_tag(@product.detail_image.url) %>
        <% end %>
      </div>
    </div>
  </div>
</section>